services:
  - type: web
    name: linkconnect
    env: python
    buildCommand: |
      curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      apt-get install -y nodejs
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python api/index.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
    autoDeploy: true 